# Generated by Django 5.2.4 on 2025-07-23 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ткани')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Себестоимость ткани (применяется ко всем цветам)', max_digits=10, verbose_name='Себестоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('color_number', models.CharField(max_length=50, verbose_name='Номер цвета')),
                ('color_hex', models.CharField(help_text='Цвет для визуального отображения (например, #FF0000)', max_length=7, verbose_name='HEX код цвета')),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за метр ширины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabric', verbose_name='Ткань')),
            ],
            options={
                'verbose_name': 'Цвет ткани',
                'verbose_name_plural': 'Цвета тканей',
                'ordering': ['fabric__name', 'color_number'],
                'unique_together': {('fabric', 'color_number')},
            },
        ),
        migrations.CreateModel(
            name='FabricRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_meters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ширина рулона (м)')),
                ('barcode', models.CharField(help_text='Уникальный штрих-код рулона', max_length=100, unique=True, verbose_name='Штрих-код')),
                ('is_active', models.BooleanField(default=True, help_text='Рулон активен (не списан со склада)', verbose_name='Активен')),
                ('created_by_admin', models.BooleanField(default=False, help_text='Рулон создан через интерфейс администратора/бухгалтера', verbose_name='Создан администратором')),
                ('is_printed', models.BooleanField(default=False, help_text='Штрих-код был распечатан', verbose_name='Распечатан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('fabric_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabriccolor', verbose_name='Цвет ткани')),
            ],
            options={
                'verbose_name': 'Рулон ткани',
                'verbose_name_plural': 'Рулоны тканей',
                'ordering': ['-created_at'],
            },
        ),
    ]
