# Generated by Django 5.0.4 on 2025-07-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0003_remove_fabricroll_is_printed_fabric_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabriccolor',
            name='price_per_meter',
        ),
        migrations.AlterField(
            model_name='fabriccolor',
            name='color_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер цвета'),
        ),
    ]
