# Generated by Django 4.2.23 on 2025-07-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0004_remove_fabriccolor_price_per_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена, по которой ткань продается клиентам', max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
    ]
