# Generated by Django 4.2.23 on 2025-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0006_add_description_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительное описание ткани', verbose_name='Описание'),
        ),
    ]
