# Generated by Django 5.0.4 on 2025-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending_payment', 'Ожидание оплаты'), ('paid', 'Оплачен')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
