# Generated by Django 4.2.23 on 2025-09-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_total_amount_alter_deal_total_with_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealitem',
            name='fixed_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Себестоимость ткани зафиксированная на момент создания позиции', max_digits=10, null=True, verbose_name='Себестоимость на момент сделки (₸/м)'),
        ),
    ]
