# Generated by Django 4.2.23 on 2025-10-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Краткое название или никнейм клиента', max_length=200, verbose_name='Никнейм / Название компании')),
                ('full_name', models.CharField(blank=True, help_text='Полное имя клиента или ФИО контактного лица', max_length=255, null=True, verbose_name='Полное имя / ФИО контактного лица')),
                ('phone', models.CharField(help_text='Контактный номер телефона', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Электронная почта клиента', max_length=255, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, help_text='Физический адрес клиента', max_length=255, null=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о клиенте', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['nickname'],
            },
        ),
    ]
