# Generated by Django 5.0.4 on 2025-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, help_text='Физический адрес клиента', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Электронная почта клиента', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, help_text='Полное имя клиента или ФИО контактного лица', max_length=255, null=True, verbose_name='Полное имя / ФИО контактного лица'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительная информация о клиенте', verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(help_text='Краткое название или никнейм клиента', max_length=200, verbose_name='Никнейм / Название компании'),
        ),
    ]
