# Generated by Django 4.2.23 on 2025-07-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FabricRoll',
        ),
    ]
