# Generated by Django 5.2.4 on 2025-07-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Полное имя или никнейм клиента', max_length=200, verbose_name='ФИО клиента')),
                ('phone', models.CharField(help_text='Контактный номер телефона', max_length=20, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о клиенте', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['nickname'],
            },
        ),
    ]
