# Generated by Django 5.0.4 on 2025-07-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricroll',
            name='fabric_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_rolls_from_fabrics', to='fabrics.fabriccolor', verbose_name='Цвет ткани'),
        ),
    ]
