# Generated by Django 5.0.4 on 2025-07-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0002_alter_fabricroll_fabric_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricroll',
            name='is_printed',
        ),
        migrations.AddField(
            model_name='fabric',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительное описание ткани', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='fabricroll',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительная информация о клиенте', verbose_name='Примечания'),
        ),
    ]
