# Generated by Django 4.2.23 on 2025-07-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0008_create_fabricroll_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricroll',
            name='width_meters',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ширина рулона (м)'),
        ),
    ]
