# Generated by Django 4.2.23 on 2025-07-29 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0009_alter_fabricroll_width_meters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabriccolor',
            name='color_hex',
        ),
    ]
