# Generated by Django 4.2.23 on 2025-07-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0010_remove_color_hex_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabriccolor',
            name='color_hex',
            field=models.CharField(default='#CCCCCC', help_text='Цвет для визуального отображения (например, #FF0000)', max_length=7, verbose_name='HEX код цвета'),
        ),
    ]
