# Generated by Django 5.0.4 on 2025-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='Ставка НДС (%)')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
