# Generated by Django 4.2.23 on 2025-10-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='Ставка НДС (%)')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Автоматическая наценка (%)')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
