# Generated by Django 4.2.23 on 2025-07-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Автоматическая наценка (%)'),
        ),
    ]
