# Generated by Django 5.2.4 on 2025-07-23 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_number', models.CharField(help_text='Автоматически генерируемый номер заказа', max_length=50, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('waiting_payment', 'Ожидание оплаты'), ('paid', 'Оплачен')], default='created', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма без НДС (₸)')),
                ('total_with_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма с НДС (₸)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_meters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ширина (м)')),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за метр ширины (₸)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (₸)')),
                ('position_number', models.PositiveIntegerField(verbose_name='Номер позиции')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal', verbose_name='Заказ')),
                ('fabric_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabriccolor', verbose_name='Цвет ткани')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
                'ordering': ['position_number'],
            },
        ),
    ]
