# Generated by Django 5.0.4 on 2025-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма без НДС (₸)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма с НДС (₸)'),
        ),
    ]
